import { writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { glob } from "glob";

const scriptsDir = join(process.cwd(), "scripts");
const projectDir = join(process.cwd(), "src");

const translationsByTier = JSON.parse(
  readFileSync(join(scriptsDir, "scraped-translations-by-tier.json"), "utf-8"),
);
const translationsByText = JSON.parse(
  readFileSync(join(scriptsDir, "scraped-translations-by-text.json"), "utf-8"),
);

console.log("🔍 Generating complete-affix-translations.ts with Tier support\n");

const translationsByTierKeys = new Set(Object.keys(translationsByTier));
const translationsByTextKeys = new Set(Object.keys(translationsByText));

const gearFiles = glob.sync(join(projectDir, "data/gear-affix/*.ts"));

let totalAffixes = 0;
let foundByTier = 0;
let foundByText = 0;
let notFound: { file: string; tier: string; affix: string }[] = [];

const tierTranslations: Record<string, string> = {};
const textTranslations: Record<string, string> = {};

gearFiles.forEach((file) => {
  const content = readFileSync(file, "utf-8");
  const fileName = file.split("/").pop()?.replace(".ts", "") || "";

  const tierMatches = content.match(/tier:\s*"(\d+)"/g) || [];
  const affixMatches = content.match(/craftableAffix:\s*"([^"]+)"/g) || [];

  for (let i = 0; i < affixMatches.length; i++) {
    const tierMatch = tierMatches[i];
    const affixMatch = affixMatches[i];

    const tier = tierMatch ? tierMatch.match(/tier:\s*"(\d+)"/)[1] : "0";
    const affix = affixMatch.match(/craftableAffix:\s*"([^"]+)"/)[1];

    totalAffixes++;

    const tierKey = `${fileName}|${tier}|${affix}`;

    if (translationsByTierKeys.has(tierKey)) {
      foundByTier++;
      tierTranslations[tierKey] = translationsByTier[tierKey];
      if (!textTranslations[affix]) {
        textTranslations[affix] = translationsByTier[tierKey];
      }
    } else if (translationsByTextKeys.has(affix)) {
      foundByText++;
      if (!textTranslations[affix]) {
        textTranslations[affix] = translationsByText[affix];
      }
    } else {
      notFound.push({ file: fileName, tier, affix });
    }
  }
});

console.log("=".repeat(60));
console.log("\n📊 Results:");
console.log(`   Total affixes in gear-affix/*.ts: ${totalAffixes}`);
console.log(`   Found by Tier: ${foundByTier}`);
console.log(`   Found by Text: ${foundByText}`);
console.log(`   NOT found: ${notFound.length}`);
console.log(
  `   Coverage: ${(((foundByTier + foundByText) / totalAffixes) * 100).toFixed(1)}%`,
);

const outputFile = join(
  projectDir,
  "data/translated-affixes/complete-affix-translations.ts",
);

const tsContent = `// This file is auto-generated by scrape-affix-translations-v3.ts
// Do not modify manually
// Last updated: ${new Date().toISOString()}

// Translations by Tier (equipmentType|tier|affix -> cn)
export const AFFIX_TRANSLATIONS_BY_TIER: Record<string, string> = {
${Object.entries(tierTranslations)
  .map(
    ([key, cn]) =>
      `  "${key.replace(/"/g, '\\"')}": "${cn.replace(/"/g, '\\"')}",`,
  )
  .join("\n")}
} as const;

// Translations by Text only (fallback)
export const AFFIX_TRANSLATIONS_BY_TEXT: Record<string, string> = {
${Object.entries(textTranslations)
  .map(
    ([en, cn]) =>
      `  "${en.replace(/"/g, '\\"')}": "${cn.replace(/"/g, '\\"')}",`,
  )
  .join("\n")}
} as const;

// Missing translations
export const MISSING_TRANSLATIONS: readonly { file: string; tier: string; affix: string }[] = [
${notFound
  .slice(0, 100)
  .map(
    (item) =>
      `  { file: "${item.file}", tier: "${item.tier}", affix: "${item.affix.replace(/"/g, '\\"')}" },`,
  )
  .join("\n")}
${notFound.length > 100 ? `\n  // ... and ${notFound.length - 100} more` : ""}
] as const;
`;

writeFileSync(outputFile, tsContent, "utf-8");
console.log(`\n✅ Generated ${outputFile}`);

writeFileSync(
  join(scriptsDir, "missing-translations-v2.json"),
  JSON.stringify(notFound, null, 2),
  "utf-8",
);
console.log(
  `✅ Saved missing translations to ${join(scriptsDir, "missing-translations-v2.json")}`,
);

console.log("\n📋 Sample translations by Tier (first 10):");
Object.entries(tierTranslations)
  .slice(0, 10)
  .forEach(([key, cn]) => {
    console.log(`   "${key}" → "${cn}"`);
  });

console.log("\n📋 Sample missing (first 10):");
notFound.slice(0, 10).forEach((item) => {
  console.log(`   [${item.file}] Tier ${item.tier}: ${item.affix}`);
});
