import { writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { glob } from "glob";

const scriptsDir = join(process.cwd(), "scripts");
const projectDir = join(process.cwd(), "src");

const scrapedTranslations = JSON.parse(
  readFileSync(join(scriptsDir, "scraped-translations.json"), "utf-8"),
);

console.log("🔍 Generating complete-affix-translations.ts\n");

const scrapedKeys = new Set(Object.keys(scrapedTranslations));

const gearFiles = glob.sync(join(projectDir, "data/gear-affix/*.ts"));

let totalAffixes = 0;
let foundInScraped = 0;
const notFound: string[] = [];

const allTranslations: Record<string, string> = {};

gearFiles.forEach((file) => {
  const content = readFileSync(file, "utf-8");
  const craftableAffixMatches =
    content.match(/craftableAffix:\s*"([^"]+)"/g) || [];

  craftableAffixMatches.forEach((match) => {
    const affix = match.match(/craftableAffix:\s*"([^"]+)"/)[1];
    totalAffixes++;

    if (scrapedKeys.has(affix)) {
      foundInScraped++;
      allTranslations[affix] = scrapedTranslations[affix];
    } else {
      notFound.push(affix);
    }
  });
});

console.log("📊 Results:");
console.log(`   Total affixes: ${totalAffixes}`);
console.log(`   Found translations: ${foundInScraped}`);
console.log(`   Missing translations: ${notFound.length}`);
console.log(
  `   Coverage: ${((foundInScraped / totalAffixes) * 100).toFixed(1)}%`,
);

const outputFile = join(
  projectDir,
  "data/translated-affixes/complete-affix-translations.ts",
);

const tsContent = `// This file is auto-generated by scrape-affix-translations.ts
// Do not modify manually
// Last updated: ${new Date().toISOString()}

export const AFFIX_NAME_TRANSLATIONS: Record<string, string> = {
${Object.entries(allTranslations)
  .map(
    ([en, cn]) =>
      `  "${en.replace(/"/g, '\\"')}": "${cn.replace(/"/g, '\\"')}",`,
  )
  .join("\n")}
} as const;

export const MISSING_TRANSLATIONS: readonly string[] = [
${notFound.map((affix) => `  "${affix.replace(/"/g, '\\"')}",`).join("\n")}
] as const;
`;

writeFileSync(outputFile, tsContent, "utf-8");
console.log(`\n✅ Generated ${outputFile}`);

writeFileSync(
  join(scriptsDir, "missing-translations.json"),
  JSON.stringify(notFound, null, 2),
  "utf-8",
);
console.log(
  `✅ Saved missing translations to ${join(scriptsDir, "missing-translations.json")}`,
);

console.log("\n📋 Sample translations (first 10):");
Object.entries(allTranslations)
  .slice(0, 10)
  .forEach(([en, cn]) => {
    console.log(`   "${en}" → "${cn}"`);
  });

console.log("\n📋 Sample missing translations (first 10):");
notFound.slice(0, 10).forEach((affix) => {
  console.log(`   "${affix}"`);
});
