import { writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

const scriptsDir = join(process.cwd(), "scripts");
const projectDir = join(process.cwd(), "src");

const scrapedTranslations = JSON.parse(
  readFileSync(join(scriptsDir, "scraped-full-objects.json"), "utf-8"),
);

console.log("🔍 Generating complete-affix-translations.ts with full objects\n");

console.log(`Total scraped translations: ${Object.keys(scrapedTranslations).length}`);

const outputFile = join(
  projectDir,
  "data/translated-affixes/complete-affix-translations.ts",
);

const tsContent = `// This file is auto-generated by scrape-full-objects.ts
// Do not modify manually
// Last updated: ${new Date().toISOString()}

// Translation table: Key (EN object as JSON) -> Value (CN object)
// Usage: AFFIX_TRANSLATIONS[JSON.stringify(enAffix)] = cnAffix

export const AFFIX_TRANSLATIONS: Record<string, {
  equipmentSlot: string;
  equipmentType: string;
  affixType: string;
  craftingPool: string;
  tier: string;
  craftableAffix: string;
}> = ${JSON.stringify(scrapedTranslations, null, 2)} as const;

// Alias for backwards compatibility
export const AFFIX_NAME_TRANSLATIONS = AFFIX_TRANSLATIONS;
`;

writeFileSync(outputFile, tsContent, "utf-8");
console.log(`\n✅ Generated ${outputFile}`);

console.log("\n📋 Sample translations (first 5):");
const entries = Object.entries(scrapedTranslations);
entries.slice(0, 5).forEach(([key, value]) => {
  const enObj = JSON.parse(key);
  console.log(`\nEN: { equipmentType: "${enObj.equipmentType}", tier: "${enObj.tier}", craftableAffix: "${enObj.craftableAffix}" }`);
  console.log(`CN: { equipmentType: "${value.equipmentType}", tier: "${value.tier}", craftableAffix: "${value.craftableAffix}" }`);
});
